#!/usr/bin/env python3
"""Generate the OliSe Player logo in FastTracker II style.

Bold italic lettering with a 3D extrusion, a grey/blue chrome front face,
dithered down to a small palette and crisp pixels. Writes:
  assets/logo.png     preview / README image (RGBA)
  src/logo_data.h     LOGO_W, LOGO_H and LOGO_PX[] (ARGB, straight alpha)

Usage: tools/make_logo.py [text] [max_width]
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/ubuntu/Ubuntu-BI.ttf",
    "/usr/share/fonts/opentype/urw-base35/NimbusSans-BoldItalic.otf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf",
]

# Front face gradient (top -> bottom), sampled per row of the glyph box.
CHROME = [
    (0x9c, 0x9c, 0xb8),  # cool grey top
    (0xd8, 0xd8, 0xec),
    (0xf4, 0xf4, 0xff),  # shine band
    (0xc0, 0xc0, 0xd8),
    (0x70, 0x70, 0x90),  # dark middle (horizon)
    (0x58, 0x58, 0x78),
    (0x9c, 0x9c, 0xb8),
    (0xd0, 0xd0, 0xe4),  # light bottom
]
EXTRUDE_TOP = (0x50, 0x50, 0x6c)
EXTRUDE_BOTTOM = (0x24, 0x24, 0x38)
OUTLINE = (0x14, 0x14, 0x24)


def pick_font(size):
    for path in FONT_CANDIDATES:
        if os.path.exists(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def gradient_color(t):
    """t in [0,1] -> colour along CHROME with linear interpolation."""
    t = max(0.0, min(1.0, t)) * (len(CHROME) - 1)
    i = int(t)
    f = t - i
    a = CHROME[i]
    b = CHROME[min(i + 1, len(CHROME) - 1)]
    return tuple(int(a[k] + (b[k] - a[k]) * f) for k in range(3))


def render(text, max_width):
    scale = 4                     # supersample, then reduce to pixel art
    font = pick_font(240)
    probe = Image.new("L", (10, 10))
    bbox = ImageDraw.Draw(probe).textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    depth = 28                    # extrusion depth at supersample scale
    pad = 16
    W, H = tw + depth + pad * 2, th + depth + pad * 2

    mask = Image.new("L", (W, H), 0)
    ImageDraw.Draw(mask).text((pad - bbox[0], pad - bbox[1]), text, font=font, fill=255)

    out = Image.new("RGBA", (W, H), (0, 0, 0, 0))

    # Extrusion: stacked copies shifted down-right, dark grey to darker.
    for d in range(depth, 0, -1):
        t = d / depth
        col = tuple(int(EXTRUDE_TOP[k] + (EXTRUDE_BOTTOM[k] - EXTRUDE_TOP[k]) * t) for k in range(3))
        layer = Image.new("RGBA", (W, H), col + (255,))
        shifted = Image.new("L", (W, H), 0)
        shifted.paste(mask, (d, d))
        out.paste(layer, (0, 0), shifted)

    # Front face: vertical chrome gradient over the glyph box.
    face = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    fpx = face.load()
    mpx = mask.load()
    y_top, y_bot = pad, pad + th
    for y in range(H):
        t = (y - y_top) / max(1, (y_bot - y_top))
        col = gradient_color(t)
        for x in range(W):
            if mpx[x, y]:
                fpx[x, y] = col + (mpx[x, y],)
    out.alpha_composite(face)

    # Outline: dilate the alpha and paint the ring dark.
    alpha = out.split()[3]
    ring = alpha.filter(ImageFilter.MaxFilter(9))
    outline = Image.new("RGBA", (W, H), OUTLINE + (255,))
    base = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    base.paste(outline, (0, 0), ring)
    base.alpha_composite(out)
    out = base

    # Reduce to the target width with a box filter (keeps edges soft), then
    # quantize the colours so it looks like a hand-pixelled 16-colour logo.
    target_w = max_width
    target_h = int(H * target_w / W)
    small = out.resize((target_w, target_h), Image.BOX)
    rgb = small.convert("RGB").quantize(colors=24, dither=Image.FLOYDSTEINBERG).convert("RGB")
    a = small.split()[3].point(lambda v: 255 if v > 110 else 0)
    final = Image.merge("RGBA", (*rgb.split(), a))
    return final


def write_header(img, path):
    w, h = img.size
    px = img.load()
    with open(path, "w") as f:
        f.write("/* Generated by tools/make_logo.py. Do not edit. */\n")
        f.write("#ifndef LOGO_DATA_H\n#define LOGO_DATA_H\n#include <stdint.h>\n")
        f.write(f"#define LOGO_W {w}\n#define LOGO_H {h}\n")
        f.write("static const uint32_t LOGO_PX[LOGO_W * LOGO_H] = {\n")
        for y in range(h):
            row = []
            for x in range(w):
                r, g, b, a = px[x, y]
                row.append("0x%02x%02x%02x%02x" % (a, r, g, b) if a else "0")
            f.write(",".join(row) + ",\n")
        f.write("};\n#endif\n")


def main():
    text = sys.argv[1] if len(sys.argv) > 1 else "OliSe Player"
    max_width = int(sys.argv[2]) if len(sys.argv) > 2 else 440
    img = render(text, max_width)
    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    img.save(os.path.join(ROOT, "assets", "logo.png"))
    write_header(img, os.path.join(ROOT, "src", "logo_data.h"))
    print("logo:", img.size)


if __name__ == "__main__":
    main()
